name: 'Tests: node.js 10 - 20'

on: [pull_request, push]

permissions:
  contents: read

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@70adccb87a0cc9b369070083adbeac469929c9fe
    with:
      range: '>= 10 < 20'
      type: minors
      command: npm run tests-only
